local Players = game:GetService("Players")

local Regions = {
   US="USA",CA="CANADA",MX="MEXICO",BR="BRAZIL",AR="ARGENTINA",
   CO="COLOMBIA",VE="VENEZUELA",EC="ECUADOR",BO="BOLIVIA",
   PY="PARAGUAY",UY="URUGUAY",GY="GUYANA",SR="SURINAME",
   TT="TRINIDAD AND TOBAGO",JM="JAMAICA",BB="BARBADOS",
   BS="BAHAMAS",GD="GRENADA",LC="SAINT LUCIA",
   VC="SAINT VINCENT AND THE GRENADINES",
   AG="ANTIGUA AND BARBUDA",KN="SAINT KITTS AND NEVIS",
   DM="DOMINICA",HT="HAITI",DO="DOMINICAN REPUBLIC",
   CU="CUBA",PR="PUERTO RICO",

   GB="UNITED KINGDOM",IE="IRELAND",FR="FRANCE",DE="GERMANY",
   IT="ITALY",ES="SPAIN",PT="PORTUGAL",NL="NETHERLANDS",
   BE="BELGIUM",LU="LUXEMBOURG",CH="SWITZERLAND",AT="AUSTRIA",
   SE="SWEDEN",NO="NORWAY",FI="FINLAND",DK="DENMARK",
   IS="ICELAND",PL="POLAND",CZ="CZECHIA",SK="SLOVAKIA",
   HU="HUNGARY",RO="ROMANIA",BG="BULGARIA",GR="GREECE",
   HR="CROATIA",SI="SLOVENIA",RS="SERBIA",BA="BOSNIA",
   MK="NORTH MACEDONIA",AL="ALBANIA",ME="MONTENEGRO",
   EE="ESTONIA",LV="LATVIA",LT="LITHUANIA",

   RU="RUSSIA",UA="UKRAINE",BY="BELARUS",MD="MOLDOVA",
   GE="GEORGIA",AM="ARMENIA",AZ="AZERBAIJAN",
   KZ="KAZAKHSTAN",UZ="UZBEKISTAN",TM="TURKMENISTAN",
   KG="KYRGYZSTAN",TJ="TAJIKISTAN",

   TR="TURKEY",CY="CYPRUS",

   SA="SAUDI ARABIA",AE="UAE",QA="QATAR",KW="KUWAIT",
   OM="OMAN",BH="BAHRAIN",JO="JORDAN",IL="ISRAEL",
   IQ="IRAQ",IR="IRAN",SY="SYRIA",LB="LEBANON",
   YE="YEMEN",EG="EGYPT",

   IN="INDIA",PK="PAKISTAN",BD="BANGLADESH",LK="SRI LANKA",
   NP="NEPAL",BT="BHUTAN",AF="AFGHANISTAN",MV="MALDIVES",

   ID="INDONESIA",PH="PHILIPPINES",TH="THAILAND",
   VN="VIETNAM",LA="LAOS",KH="CAMBODIA",MM="MYANMAR",
   MY="MALAYSIA",SG="SINGAPORE",BN="BRUNEI",
   JP="JAPAN",KR="SOUTH KOREA",CN="CHINA",HK="HONG KONG",
   MO="MACAU",TW="TAIWAN",MN="MONGOLIA",

   AU="AUSTRALIA",NZ="NEW ZEALAND",PG="PAPUA NEW GUINEA",
   FJ="FIJI",SB="SOLOMON ISLANDS",WS="SAMOA",TO="TONGA",

   NG="NIGERIA",GH="GHANA",KE="KENYA",UG="UGANDA",
   TZ="TANZANIA",RW="RWANDA",BI="BURUNDI",
   ET="ETHIOPIA",SO="SOMALIA",SD="SUDAN",
   DZ="ALGERIA",MA="MOROCCO",TN="TUNISIA",LY="LIBYA",
   SN="SENEGAL",CI="IVORY COAST",CM="CAMEROON",
   ZA="SOUTH AFRICA",ZW="ZIMBABWE",ZM="ZAMBIA",
   BW="BOTSWANA",NA="NAMIBIA",MZ="MOZAMBIQUE"
}

for _,plr in Players:GetPlayers() do
   local r=plr:GetAttribute("Region")
   local d=plr:GetAttribute("DeviceServer")
   if r then
      print(
         plr.DisplayName..
         " is From: "..
         (Regions[r] or r)..
         " | "..
         tostring(d or "Unknown")
      )
   end
  end
